# Generated by Django 3.1.4 on 2020-12-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_source', models.FileField(upload_to='uploads/')),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auditorium.auditorium')),
            ],
        ),
    ]
