# Generated by Django 3.1.4 on 2020-12-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='role',
            field=models.ForeignKey(default='attendee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='roles.role'),
        ),
    ]
